name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Haskell (GHC + Stack)
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.6.*"
          enable-stack: true
          stack-version: "latest"

      - name: Cache Stack (global and local)
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build
        run: stack build --no-terminal --system-ghc

      - name: Test (with coverage)
        run: stack test --no-terminal --system-ghc --coverage

      - name: Build executable via Makefile (glados)
        run: |
          if [ -f Makefile ]; then
            make all
          else
            echo "No Makefile found, skipping Make build"
          fi

      - name: Smoke check
        run: |
          if [ -x ./glados ]; then
            ./glados --version || echo "glados built, --version not implemented"
          else
            echo "glados binary not found, skipping smoke check"
          fi

      - name: Locate coverage directory
        run: echo "HPC_DIR=$(stack path --local-hpc-root)" >> $GITHUB_ENV

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: ${{ env.HPC_DIR }}/**/*
          if-no-files-found: ignore

      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: glados-${{ runner.os }}
          path: glados
          if-no-files-found: ignore
